# Input data
glodap: "input_data/window_data_from_GLODAPv2.2023.csv"
BAS_prealpha: "input_data/pre_alpha_AISIT_0.1.4.csv"

# Save training data
scaler: "glodap_models/scaler.save"
oxygen_weights: "glodap_models/oxygen18_model_{m}.pth"
mse_plots: "glodap_models/oxygen18_mse_epoch_model_{m}.png"

# Model data
arctic_reanalysis: "/noc/mpoc/surface/acable/arctic_ocean_reanalysis/aor_ts.nc"
arctic_reanalysis_oxy: "/noc/mpoc/surface/acable/arctic_ocean_reanalysis/aor_oxy.nc"

# AOO index
aoo_index: "/noc/users/acable/AISIT/aoo_index.csv"